// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.17.3
// source: dummy/dummy.proto

package dummy

import (
	reflect "reflect"
	sync "sync"

	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SayRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Word string `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
}

func (x *SayRequest) Reset() {
	*x = SayRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dummy_dummy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayRequest) ProtoMessage() {}

func (x *SayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dummy_dummy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayRequest.ProtoReflect.Descriptor instead.
func (*SayRequest) Descriptor() ([]byte, []int) {
	return file_dummy_dummy_proto_rawDescGZIP(), []int{0}
}

func (x *SayRequest) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

type SayResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DoubleWord string `protobuf:"bytes,1,opt,name=double_word,json=doubleWord,proto3" json:"double_word,omitempty"`
}

func (x *SayResponse) Reset() {
	*x = SayResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dummy_dummy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayResponse) ProtoMessage() {}

func (x *SayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dummy_dummy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayResponse.ProtoReflect.Descriptor instead.
func (*SayResponse) Descriptor() ([]byte, []int) {
	return file_dummy_dummy_proto_rawDescGZIP(), []int{1}
}

func (x *SayResponse) GetDoubleWord() string {
	if x != nil {
		return x.DoubleWord
	}
	return ""
}

var File_dummy_dummy_proto protoreflect.FileDescriptor

var file_dummy_dummy_proto_rawDesc = []byte{
	0x0a, 0x11, 0x64, 0x75, 0x6d, 0x6d, 0x79, 0x2f, 0x64, 0x75, 0x6d, 0x6d, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x64, 0x75, 0x6d, 0x6d, 0x79, 0x22, 0x20, 0x0a, 0x0a, 0x53, 0x61,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x6f, 0x72, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x2e, 0x0a, 0x0b,
	0x53, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x64,
	0x6f, 0x75, 0x62, 0x6c, 0x65, 0x5f, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x57, 0x6f, 0x72, 0x64, 0x32, 0x37, 0x0a, 0x05,
	0x44, 0x75, 0x6d, 0x6d, 0x79, 0x12, 0x2e, 0x0a, 0x03, 0x53, 0x61, 0x79, 0x12, 0x11, 0x2e, 0x64,
	0x75, 0x6d, 0x6d, 0x79, 0x2e, 0x53, 0x61, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x12, 0x2e, 0x64, 0x75, 0x6d, 0x6d, 0x79, 0x2e, 0x53, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x75, 0x6c, 0x69, 0x61, 0x6f, 0x67, 0x72, 0x69, 0x73, 0x2f, 0x67,
	0x75, 0x70, 0x70, 0x79, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x64, 0x75, 0x6d, 0x6d, 0x79, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dummy_dummy_proto_rawDescOnce sync.Once
	file_dummy_dummy_proto_rawDescData = file_dummy_dummy_proto_rawDesc
)

func file_dummy_dummy_proto_rawDescGZIP() []byte {
	file_dummy_dummy_proto_rawDescOnce.Do(func() {
		file_dummy_dummy_proto_rawDescData = protoimpl.X.CompressGZIP(file_dummy_dummy_proto_rawDescData)
	})
	return file_dummy_dummy_proto_rawDescData
}

var file_dummy_dummy_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_dummy_dummy_proto_goTypes = []interface{}{
	(*SayRequest)(nil),  // 0: dummy.SayRequest
	(*SayResponse)(nil), // 1: dummy.SayResponse
}
var file_dummy_dummy_proto_depIdxs = []int32{
	0, // 0: dummy.Dummy.Say:input_type -> dummy.SayRequest
	1, // 1: dummy.Dummy.Say:output_type -> dummy.SayResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dummy_dummy_proto_init() }
func file_dummy_dummy_proto_init() {
	if File_dummy_dummy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dummy_dummy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SayRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dummy_dummy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SayResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dummy_dummy_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dummy_dummy_proto_goTypes,
		DependencyIndexes: file_dummy_dummy_proto_depIdxs,
		MessageInfos:      file_dummy_dummy_proto_msgTypes,
	}.Build()
	File_dummy_dummy_proto = out.File
	file_dummy_dummy_proto_rawDesc = nil
	file_dummy_dummy_proto_goTypes = nil
	file_dummy_dummy_proto_depIdxs = nil
}
